version: "2"

services:
  woocommerce:
    build:
      dockerfile: Dockerfile
      context: ./
    depends_on:
      - db
    volumes:
      - ./:/paylater
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=password
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_URL=woocommerce.docker:8090
      - WORDPRESS_SITE_NAME=PmtWooCommerce
      - WORDPRESS_ADMIN_EMAIL=demo@woocommerceshop.com
      - WORDPRESS_ADMIN_USER=admin
      - WORDPRESS_ADMIN_PASSWORD=admin
    ports:
      - "8090:80"
    networks:
      - internal
      - public

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wordpress
    networks:
      - internal

networks:
  internal:
  public: